# Docker Compose for PRODUCTION
# Usage: docker-compose up

services:
  # React Frontend (Vite) - Production Build
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: davetim-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - davetim-network

networks:
  davetim-network:
    driver: bridge